apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-zrs0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-zrs0
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-zrs0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-zrs0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-zrs0
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gmmb-tenant/rhtap-demo-app/hacbs-test-project-zrs0@sha256:696d36140611cb7d924490223d4647bc6eaa24662e51b9bcea483f1190e9e03a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
